[package]
build = "build.rs"
edition = "2021"
name = "fuver"
version = "0.3.4"

[dependencies]
clap = {version = "4.5.27", features = ["derive"]}
serde = {version = "1.0", features = ["derive"]}
toml = {version = "0.8.20"}
