[version]
major = 0
minor = 11
patch = 4
str = "0.11.4"

[pre]
tag = "beta"

[build]
number = 600
date = "2025-03-04T01:14:25.102948100+09:00"
hash = "cc5048825cf821ae2a8db3eeadbaed9f548cc04a"
format = "build.{number}.{date:%Y%m%d}"
